---

- name: Solve control node
  hosts: controller
  vars:
    USER: rhel
  environment:
    CONTROLLER_HOST: https://localhost:8443
    CONTROLLER_USERNAME: admin
    CONTROLLER_PASSWORD: ansible123!
    CONTROLLER_VERIFY_SSL: false

  tasks:
    - name: Create your first apache playbooks Project from git
      awx.awx.project:
        name: "Apache playbooks"
        organization: Default
        state: present
        scm_type: git
        scm_url: https://github.com/leogallego/instruqt-wyfp.git
