---
- name: Validation control node
  hosts: controller
  vars:
    USER: rhel
  environment:
    CONTROLLER_HOST: https://localhost:8443
    CONTROLLER_USERNAME: admin
    CONTROLLER_PASSWORD: ansible123!
    CONTROLLER_VERIFY_SSL: false

  tasks:
    - name: Check your first Project from git
      awx.awx.project:
        name: "Apache playbooks"
        organization: Default
        state: present
        scm_type: git
        scm_url: https://github.com/leogallego/instruqt-wyfp.git
      check_mode: true
      register: check_proj

    - name: Validate groups and nodes in the inventory
      validation_check:
        error_msg: "The Project 'Apache playbooks' does not exists"
        check: not check_proj.changed
