---

antora:
  name: modules
  dir: www
  modules:
    - name: 01-dashboard
      label: Controller Dashboard
      solveButton: true
    - name: 02-inventory
      label: Create an Inventory
      solveButton: true
    - name: 03-controller-getting-started-jt
      label: Using job templates
      solveButton: true

tabs:
  - name: Controller
    port: 8443
    path: /#/login
  - name: ">_control"
    port: 443
    path: /tty1
  - name: VSCode Editor
    port: 8443
    path: /editor/?folder=/home/rhel

  