---

- name: Solve control node
  hosts: controller
  vars:
    USER: rhel
  environment:
    CONTROLLER_HOST: https://localhost:8443
    CONTROLLER_USERNAME: admin
    CONTROLLER_PASSWORD: ansible123!
    CONTROLLER_VERIFY_SSL: false

  tasks:
    - name: Create an inventory in automation controller
      awx.awx.inventory:
        name: Lab-Inventory
        organization: Default

    - name: Add node1 and node2 to Lab-Inventory
      awx.awx.host:
        name: "{{ item }}"
        inventory: Lab-Inventory
        state: present
      loop:
        - node1
        - node2

    - name: Create web group and add node1 and node2
      awx.awx.group:
        name: web
        inventory: Lab-Inventory
        hosts:
          - node1
          - node2
