---

- name: Solve control node
  hosts: controller
  vars:
    USER: rhel
  environment:
    CONTROLLER_HOST: https://localhost:8443
    CONTROLLER_USERNAME: admin
    CONTROLLER_PASSWORD: ansible123!
    CONTROLLER_VERIFY_SSL: false
  tasks:
    - name: Create a second Project from git, additional playbooks
      awx.awx.project:
        name: "Additional playbooks"
        organization: Default
        state: present
        scm_type: git
        scm_url: https://github.com/leogallego/instruqt-wyfp-additional.git

    - name: Launch additional playbooks project sync
      awx.awx.project_update:
        project: "Additional playbooks"
        wait: true
